python caveman.py \
    --logs test_logs \
    --read-count 350000 \
    --outdir /lustre/scratch125/casm/teams/team78/td14/panprostate/test_caveman_py \
    --reference /lustre/scratch127/casm/staging/panprostate/ref/genome_ignored.fa.fai \
    --tumour-bam /lustre/scratch127/casm/staging/panprostate/PPCG0345a/PPCG0345a.cram \
    --normal-bam /lustre/scratch127/casm/staging/panprostate/PPCG0345b/PPCG0345b.cram \
    --ignore-file /lustre/scratch127/casm/staging/panprostate/ref/caveman/HiDepth.tsv \
    --tumour-cn /lustre/scratch127/casm/projects/panprostate/PPCG0345b_vs_PPCG0345a/ascat/tumor.cn.bed \
    --normal-cn /lustre/scratch127/casm/staging/panprostate/PPCG0345b/PPCG0345b.cram \
    --species Human \
    --species-assembly NCBI38 \
    --flag-bed /lustre/scratch127/casm/staging/panprostate/ref/caveman/flagging \
    --unmatched-vcf /lustre/scratch127/casm/staging/panprostate/ref/caveman/ \
    --seqType genome \
    --normal-contamination /lustre/scratch127/casm/projects/panprostate/PPCG0345b_vs_PPCG0345a/ascat/PPCG0345a.samplestatistics.txt \
    --normal-protocol WGS \
    --tumour-protocol WGS \
    --flagConfig /lustre/scratch127/casm/staging/panprostate/ref/caveman/flag.vcf.config.WGS.ini \
    --flagToVcfConfig /lustre/scratch127/casm/staging/panprostate/ref/caveman/flagging/flag.to.vcf.convert.ini \
    --tum-cn-default 5 \
    --norm-cn-default 2 \
    --threads 10 \
    --process setup \
    --noflag \
    --noclean
